# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20170107_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='img_url',
        ),
        migrations.AddField(
            model_name='location',
            name='img',
            field=models.ImageField(default=b'location_images/default.png', upload_to=b'location_images'),
        ),
    ]
